[workspace]

members = ["gamiscreen-client", "gamiscreen-server", "gamiscreen-shared"]
resolver = "3"

[workspace.package]
version = "0.11.0-dev.8"
edition = "2024"
authors = ["Lukasz Klimek"]
license = "GPL-3.0"
rust-version = "1.91"
